app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return redirect(route('jobs.index'));
});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::get('/home', 'HomeController@index');

    Route::resource('jobs', 'JobsController');

    Route::patch('/jobs/{id}/status/{status}', [
        'as' => 'jobs.status',
        'uses' => 'JobsController@setStatus'
    ]);

    Route::get('/jobs/{id}/moderate', [
        'as' => 'jobs.moderate',
        'uses' => 'JobsController@moderate'
    ]);

    Route::get('/jobs/{id}/status/{status}', [
//        'middleware' => 'role:jobmoderator',
        'as' => 'jobs.moderate.status',
        'uses' => 'JobsController@setStatus'
    ]);


    Route::get('testmail', [
        'as' => 'testmail', 'uses' => 'HomeController@testmail'
    ]);

    Route::get('test', [
        'as' => 'test', 'uses' => 'HomeController@test'
    ]);
});

app/Job.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Job extends Model
{
    protected $fillable = ['title', 'description', 'email', 'status'];

    protected $attributes = array(
        'status' => 'pending',
    );

    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/JobCreationHistory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class JobCreationHistory extends Model
{
    protected $fillable = [
        'job_id', 'job_title', 'job_creator', 'job_creator_email'
    ];

    public function contains(User $user)
    {

    }
}

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    public function users()
    {
        return $this->hasMany('App\User');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password'
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function role()
    {
        return $this->belongsTo('App\Role');
    }

    public function jobs()
    {
        return $this->hasMany('App\Job');
    }

    public function is($role)
    {
        if ($this->role->name == $role) return true;
        return false;
    }

    public function owns($model)
    {
        if ($this->id == $model->user_id) {
            return true;
        }
        return false;
    }



}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\JobCreationHistory;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }

    public function testmail()
    {
        $data = [];

        Mail::send('emails.testmail', $data, function ($message) {
            $message->from('jobs@board.com', 'Job Board app');

            $message->to('neb.vojvodic@gmail.com');
        });

        $user = User::findOrFail(1);

        return $user;
    }

    public function test()
    {
        return count(JobCreationHistory::where('job_creator_email', 'neb.vojvodic@gmail.com')->get());
    }
}

app/Http/Controllers/JobsController.php
<?php

namespace App\Http\Controllers;

use App\Events\JobWasCreated;
use App\Http\Requests\CreateJobRequest;
use App\Http\Requests\SetJobStatusRequest;
use App\Job;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Event;
use Symfony\Component\HttpFoundation\Response;

class JobsController extends Controller
{
    public function __construct()
    {
        $this->middleware('role', [['hrmanager'], 'only' => 'setstatus, moderate']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::check()) {
            $jobs = Job::all();
        } else {
            $jobs = Job::where('status', 'published')->get();
        }

        return view('jobs.index', compact('jobs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->cannot('create-job')) {
            return redirect(route('jobs.index'));
        }

        return view('jobs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateJobRequest $request)
    {
        $user = Auth::user();

        $job = Job::create($request->all());

        $job->status = 'pending';

        $user->jobs()->save($job);

        flash()->success('You have created a new job.');

        Event::fire(new JobWasCreated($job));

        return redirect(route('jobs.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $job = Job::findOrFail($id);

        if ($job->status == 'pending' && Auth::guest()) {
            return redirect(route('jobs.index'));
        }

        return view('jobs.show', compact('job'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $job = Job::findOrFail($id);

        if (Auth::user()->cannot('edit-job', $job)) {
            return redirect(route('jobs.index'));
        }

        return view('jobs.edit', compact('job'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CreateJobRequest $request, $id)
    {
        $job = Job::findOrFail($id);

        if (Auth::user()->cannot('edit-job', $job)) {
            return redirect(route('jobs.index'));
        }

        $job->title = $request->get('title');
        $job->description = $request->get('description');
        $job->email = $request->get('email');

        $job->save();
//        $job = Job::updateOrCreate($request->all());

        return redirect(route('jobs.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function setStatus(Request $request, $id, $status)
    {

        $job = Job::findOrFail($id);

        $job->status = $status;
        $job->save();

        if ($request->ajax()) {
            return $job;
        }

        flash()->info('Job ' . $job->title . ' is now ' . $job->status);

        return redirect(route('jobs.index'));
    }

    public function moderate(Request $request, $id)
    {
        $job = Job::findOrFail($id);

        return view('jobs.moderate', compact('job'));
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/jobs/create.blade.php
@extends('layouts.app')

@section('addHead')
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
    <script>tinymce.init({ selector:'textarea' });</script>
@stop

@section('content')
    <div class="container">
        <div class="page-header">
            <h1>Create a job</h1>
        </div>

        <a href="{{ route('jobs.index') }}" class="btn btn-default">All jobs</a>

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">New job</div>
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" method="POST" action="{{ route('jobs.store') }}" autocomplete="off">
                            {!! csrf_field() !!}

                            <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                <label class="col-md-4 control-label">Title</label>

                                <div class="col-md-6">
                                    <input type="text" class="form-control" name="title" value="{{ old('title') }}" autocomplete="off">

                                    @if ($errors->has('title'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                                <label class="col-md-4 control-label">Description</label>

                                <div class="col-md-6">
                                    <textarea class="form-control" name="description" rows="15" cols="50">{{ old('description') }}</textarea>

                                    @if ($errors->has('description'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                                <label class="col-md-4 control-label">E-mail</label>

                                <div class="col-md-6">
                                    <input type="email" class="form-control" name="email" value="{{ old('email') }}" autocomplete="off">

                                    @if ($errors->has('email'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        <i class="fa fa-btn fa-check"></i>Create
                                    </button>

                                    <button type="reset" class="btn btn-default">
                                        <i class="fa fa-btn fa-eraser"></i>Reset
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/jobs/edit.blade.php
@extends('layouts.app')

@section('addHead')
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
    <script>tinymce.init({ selector:'textarea' });</script>
@stop

@section('content')
    <div class="container">
        <div class="page-header">
            <h1>Edit a job</h1>
        </div>

        <a href="{{ route('jobs.index') }}" class="btn btn-default">All jobs</a>

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Edit a job</div>
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" method="POST" action="{{ route('jobs.update', $job->id) }}">
                            <input type="hidden" name="_method" value="PUT">
                            {!! csrf_field() !!}

                            <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                <label class="col-md-4 control-label">Title</label>

                                <div class="col-md-6">
                                    <input type="text" class="form-control" name="title" value="{{ $job->title }}">

                                    @if ($errors->has('title'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                                <label class="col-md-4 control-label">Description</label>

                                <div class="col-md-6">
                                    <textarea class="form-control" name="description" rows="15" cols="50">
                                        {{ $job->description }}
                                    </textarea>

                                    @if ($errors->has('description'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                                <label class="col-md-4 control-label">E-mail</label>

                                <div class="col-md-6">
                                    <input type="email" class="form-control" name="email" value="{{ $job->email }}">

                                    @if ($errors->has('email'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        <i class="fa fa-btn fa-check"></i>Save
                                    </button>

                                    <button type="reset" class="btn btn-default">
                                        <i class="fa fa-btn fa-eraser"></i>Reset
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/jobs/index.blade.php
@extends('layouts.app')

@section('addHead')
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
    <script>tinymce.init({ selector:'textarea' });</script>
@stop

@section('content')
<div class="container">
    <div class="page-header">
        <h1>Jobs</h1>
    </div>

    @can('create-job')
    <p>
        <a href="{{ route('jobs.create') }}" class="btn btn-primary">Create</a>
    </p>
    @endcan

    <div class="row">
        <div class="col-md-12">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>Title</th>
                        <th>Created</th>
                        <th>By</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($jobs as $job)
                        @if($job->status == 'published')
                            <tr class="success" data-job-id="{{ $job->id }}">
                        @elseif($job->status == 'spam')
                            <tr class="danger" data-job-id="{{ $job->id }}">
                        @else
                            <tr data-job-id="{{ $job->id }}">
                        @endif
                            <td>{{ $job->id }}</td>
                            <td><a href="{{ route('jobs.show', $job->id) }}">{{ $job->title }}</a></td>
                            <td>{{ $job->created_at }}</td>
                            <td>{{ $job->user->name }}</td>
                            <td>{{ $job->status }}</td>
                            <td>
                                @can('edit-job', $job)
                                <a href="{{ route('jobs.edit', $job->id) }}" class="btn btn-default">Edit</a>
                                @endcan

                                @can('publish-job')
                                {{--<a href="{{ route('jobs.edit', $job->id) }}" class="btn btn-default">Set status</a>--}}
                                <div class="dropdown">
                                    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                        Set status
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1" data-job-id="{{ $job->id }}">
                                        <li><a href="#" data-job-status="pending"><span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span> Pending</a></li>
                                        <li><a href="#" data-job-status="published"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Publish</a></li>
                                        <li><a href="#" data-job-status="spam"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Spam</a></li>
                                        {{--<li role="separator" class="divider"></li>--}}
                                        {{--<li><a href="#" data-job-status="delete"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Delete</a></li>--}}
                                    </ul>
                                </div>
                                @endcan
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td>No jobs.</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    @endforelse
                </tbody>
                {{--<tr class="active">--}}

                {{--</tr>--}}
                {{--<tr class="success">...</tr>--}}
                {{--<tr class="warning">...</tr>--}}
                {{--<tr class="danger">...</tr>--}}
                {{--<tr class="info">...</tr>--}}
            </table>
        </div>
    </div>
</div>
@stop

@section('addJs')
    <script>
        $.ajaxSetup({
            url: "ping.php"
        });

        $('tbody a[data-job-status]').on( "click", function() {
            var status = $(this).attr('data-job-status');
            var ulelement = $(this).closest('[data-job-id]', $(this));
            var jobid = ulelement.attr('data-job-id');

            setStatus(jobid, status)
        });

        function setStatus(jobid, jobstatus){

            $.ajax({
                method: "POST",
                url: "jobs/"+jobid+"/status/"+jobstatus,
                data: {
                    _method: "PATCH",
                    jobid: jobid,
                    status: jobstatus
                },
                success: function (data) {
                    console.log(data);
                    updateJobRow(data);
                },
                fail: function (data) {
                    console.log('failed');
                }
            });
        }

        function updateJobRow(job){
            var row = $('tbody').find("tr[data-job-id='" + job.id + "']");
            setClassForJobRow(job, row);
            var statusField = row.find('td:nth-child(5)');
            statusField.text(job.status);
        }

        function setClassForJobRow(job, row){
            row.removeClass('success');
            row.removeClass('danger');

            if (job.status == 'pending') {
                return;
            }
            if (job.status == 'spam') {
                row.addClass('danger');
                return;
            }
            if (job.status == 'published') {
                row.addClass('success');
            }
            return;
        }
    </script>
@stop

resources/views/jobs/moderate.blade.php
@extends('jobs.show')

@section('moderator-options')

    <a href="{{ route('jobs.moderate.status', array($job->id, 'published')) }}" class="btn btn-xs btn-success"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Publish this job</a>
    <a href="{{ route('jobs.moderate.status', array($job->id, 'pending')) }}" class="btn btn-xs btn-default"><span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span> Mark as pending</a>
    <a href="{{ route('jobs.moderate.status', array($job->id, 'spam')) }}" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Mark as spam</a>
@overwrite

resources/views/jobs/show.blade.php
@extends('layouts.app')

@section('addHead')
    {{--<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>--}}
    {{--<script>tinymce.init({ selector:'textarea' });</script>--}}
@stop

@section('content')
    <div class="container">
        <div class="page-header">
            <h1>Job posting</h1>
        </div>

        <a href="{{ route('jobs.index') }}" class="btn btn-default">All jobs</a>

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Job posting</div>
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" method="POST" action="{{ route('jobs.update', $job->id) }}">
                            <input type="hidden" name="_method" value="PUT">
                            {!! csrf_field() !!}

                            <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                <label class="col-md-4 control-label">Title</label>

                                <div class="col-md-6">
                                    {{--<input type="text" class="form-control" name="title" value="{{ $job->title }}">--}}
                                    <div class="well">{{ $job->title }}</div>

                                    @if ($errors->has('title'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                                <label class="col-md-4 control-label">Description</label>

                                <div class="col-md-6">
                                        <div class="well">
                                            {!! $job->description !!}
                                        </div>

                                    @if ($errors->has('description'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                                <label class="col-md-4 control-label">E-mail</label>

                                <div class="col-md-6">
                                    {{--<input type="email" class="form-control" name="email" value="{{ $job->email }}">--}}
                                    <div class="well">{{ $job->email }}</div>

                                    @if ($errors->has('email'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    @can('edit-job', $job)
                                    <a href="{{ route('jobs.edit', $job->id) }}" class="btn btn-primary">
                                        <i class="fa fa-btn fa-eraser"></i>Edit
                                    </a>
                                    @endcan

                                    @section('moderator-options')
                                    @can('moderate-job')
                                    <a href="{{ route('jobs.moderate', $job->id) }}" class="btn btn-primary">
                                        <i class="fa fa-btn fa-eraser"></i>Moderate
                                    </a>
                                    @endcan
                                    @stop
                                    @yield('moderator-options')

                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/partials/flash.blade.php
@if (Session::has('flash_notification.message'))
    <div class="alert alert-{{ Session::get('flash_notification.level') }}">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>

        {{ Session::get('flash_notification.message') }}
    </div>
@endif